FROM python:3.12-slim-bullseye

WORKDIR /app

COPY requirements.frontend.txt .
RUN pip install --no-cache-dir -r requirements.frontend.txt

COPY app.py .

#Expose the port Streamlit runs on
EXPOSE 8501

CMD ["streamlit", "run", "app.py", "--server.port=8501", "--server.address=0.0.0.0"]